version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=development-secret-key
      - MONGODB_URI=mongodb://mongo:27017/chatbot
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - ./backend/downloads:/app/downloads
    depends_on:
      - mongo
    command: python app.py

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: